### PR TITLE
Fix Breaking change

### LINKED ISSUE #333: Your latest release was a breaking change, not a minor
Not sure if this was an accident, but you introduced a breaking change by renaming hooks.

Might be a good idea to introduce a quick patch to alias the old hooks. eg.

```ts
export { default as useDebouncedCallback, default as useDebouncedFn } from './useDebouncedCallback'
export { default as useThrottledCallback, default as useThrottledFn } from './useThrottledCallback'
```

### PR DESCRIPTION
**Pull request by genepaul**
## Description

Fixes #333

This reverts 544a504db8d6b58e74313090a6ae25f3df4d780d, which introduced breaking changes in `useDebouncedFn` and `useThrottledFn` by renaming them and changing their signatures. That commit can be reapplied and released as 2.0.0.

### CODE REVIEW

**Comment by genepaul** [comment]
@antonioru - can this be merged? If it can, I can submit a follow-up PR to reapply these changes as 2.0.

**Comment by antonioru** [comment]
hi @genepaul I have to apologise because this completely slipped out of my focus! Sorry about that!
Sure I'll have a look at it soon (i'm not at my computer right now)

**Comment by antonioru** [comment]
@genepaul I've merged it, thanks for your PR 
Please feel free to open a 2.0 version PR... 
I think I'll install semantic-release soon so this kind of problems won't happen again

**Comment by antonioru** [comment]
also keep in mind the github actions are failing 

https://github.com/antonioru/beautiful-react-hooks/runs/6312843262?check_suite_focus=true

**Comment by genepaul** [comment]
hm, when I run build locally it doesn't seem to fail.

Also, it looks like you merged my PR without releasing 1.2.1, which would fix this for people who are still on the 1.x of the library.

**Comment by antonioru** [comment]
@genepaul github actions should release that automatically and because - for some reason - the TS build fails it has not been released. 

That said, do you have an email and/or twitter account I can reach you out?

**Pull request merged**
